### ISSUE TITLE
net0  Error connecting to the server. Retrying in 10s (local variable 'serverVersion' referenced before assignment)

### ISSUE THREAD

**Issue by MrSuradechTH** [duino-coin/duino-coin#567]
net0  Error connecting to the server. Retrying in 10s (local variable 'serverVersion' referenced before assignment)

it alway show when mining
ver 2.4.5

**Comment by sys-256** [comment]
Did you try version 2.4.9?

**Comment by revoxhere** [comment]
Try 2.49, as Hoiboy recommended

**Comment by theerapoll** [comment]
I try v. 2.49 it show "net0  Error connecting to the server. Retrying in 10s (timed out)"

**Comment by sys-256** [comment]
> I try v. 2.49 it show "net0 Error connecting to the server. Retrying in 10s (timed out)"

@theerapoll  There are some issue's with the server, so connecting is a bit hard. Let it retry for some time, and it will probably just reconnect and start mining.

**Comment by Zelza-Sagaz** [comment]
Same happening here. "Error connecting to the server. Retrying in 10s"  [WINERROR 10060]. It keeps reconnecting for a few minutes than can't reconnect adn I have to restart the PC Miner. Using Win10 here.

**Comment by revoxhere** [comment]
Should work now.

**Comment by Rogerio69** [comment]
Alguém sabe informar porque a versão mais nova não abre no meu pc ?

**Comment by MrDark-Git** [comment]
I am still having the error in the pc miner from yesterday. I just started with duino a few days ago. I am not sure whether the error is from my side or from the server-side. 
after getting this error in my windows, I tried to run the python file in my wsl, getting the same error.
